version: '3'

services:
  distributedservice1:
    build: ./distributedservices/.
    hostname: leader
    domainname: assignment2
  distributedservice2:
    build: ./distributedservices/.
    hostname: node2
    domainname: assignment2
  distributedservice3:
    build: ./distributedservices/.
    hostname: node3
    domainname: assignment2
  distributedservice4:
    build: ./distributedservices/.
    hostname: node3
    domainname: assignment2
  distributedservice5:
    build: ./distributedservices/.
    hostname: node4
    domainname: assignment2
  distributedservice6:
    build: ./distributedservices/.
    hostname: node5
    domainname: assignment2
  distributedservice7:
    build: ./distributedservices/.
    hostname: node6
    domainname: assignment2