version: '3'

services:
  grepservice1:
    build: ./dgrepservice/.
  grepservice2:
    build: ./dgrepservice/.
  grepservice3:
    build: ./dgrepservice/.
  grepservice4:
    build: ./dgrepservice/.
  grepservice5:
    build: ./dgrepservice/.