version: '3'

services:
  distributedservice1:
    build: ./distributedservices/.
    hostname: leader
    domainname: assignment2
  distributedservice2:
    build: ./distributedservices/.
    hostname: node2
    domainname: assignment2
  distributedservice3:
    build: ./distributedservices/.
    hostname: node3
    domainname: assignment2
  distributedservice4:
    build: ./distributedservices/.
    hostname: node4
    domainname: assignment2
  distributedservice5:
    build: ./distributedservices/.
    hostname: node5
    domainname: assignment2
  distributedservice6:
    build: ./distributedservices/.
    hostname: node6
    domainname: assignment2
  distributedservice7:
    build: ./distributedservices/.
    hostname: node7
    domainname: assignment2
  distributedservice8:
    build: ./distributedservices/.
    hostname: node8
    domainname: assignment2
  distributedservice9:
    build: ./distributedservices/.
    hostname: node9
    domainname: assignment2
  distributedservice10:
    build: ./distributedservices/.
    hostname: node10
    domainname: assignment2
  distributedservice11:
    build: ./distributedservices/.
    hostname: node11
    domainname: assignment2
  distributedservice12:
    build: ./distributedservices/.
    hostname: node12
    domainname: assignment2
  distributedservice13:
    build: ./distributedservices/.
    hostname: node13
    domainname: assignment2
  distributedservice14:
    build: ./distributedservices/.
    hostname: node14
    domainname: assignment2
  distributedservice15:
    build: ./distributedservices/.
    hostname: node15
    domainname: assignment2
  distributedservice16:
    build: ./distributedservices/.
    hostname: node16
    domainname: assignment2
  distributedservice17:
    build: ./distributedservices/.
    hostname: node17
    domainname: assignment2
  distributedservice18:
    build: ./distributedservices/.
    hostname: node18
    domainname: assignment2
  distributedservice19:
    build: ./distributedservices/.
    hostname: node19
    domainname: assignment2
  distributedservice20:
    build: ./distributedservices/.
    hostname: node20
    domainname: assignment2
  distributedservice21:
    build: ./distributedservices/.
    hostname: node21
    domainname: assignment2
  distributedservice22:
    build: ./distributedservices/.
    hostname: node22
    domainname: assignment2
  distributedservice23:
    build: ./distributedservices/.
    hostname: node23
    domainname: assignment2
  distributedservice24:
    build: ./distributedservices/.
    hostname: node24
    domainname: assignment2
  distributedservice25:
    build: ./distributedservices/.
    hostname: node25
    domainname: assignment2
