version: '3'

services:
  grepservice1:
    build: ./http_server1/.
  grepservice2:
    build: ./http_server2/.
  grepservice3:
    build: ./http_server3/.
  grepservice4:
    build: ./http_server4/.
  grepservice5:
    build: ./http_server5/.