version: '3'

services:
  grepservice:
    build: .
  grepclient:
    build: ./dockerized_go_client/.
  grepclient2:
    build: ./dockerized_go_client2/.
  grepclient3:
    build: ./dockerized_go_client3/.